### ISSUE TITLE
STATIC_URL value not working in django-helpdesk

### ISSUE THREAD

**Issue by gmiddlecote** [rossp/django-helpdesk#317] opened 2015-04-09 13:34 UTC
Hi

> Latest versions of Django, Django-helpdesk in a virtual environment

The value of STATIC_URL is not appearing in the django-helpdesk pages, but its working fine in "Admin".

# Settings.py

    STATIC_URL = '/static/'
    STATIC_ROOT = '/home/ithelpdeskuser/itsupport/static/'

# Source code for django-helpdesk main page

    <link rel='stylesheet' href='helpdesk/helpdesk-extend.css' type='text/css' />

This shows up as 404 errors

# Source code for Admin main page

    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/login.css" />

This works perfectly in Admin.

How do I fix it in django-helpdesk.

Thanks
George

**Comment by rossp** [comment] 2015-04-09 22:46
What context processors have you got configured?

**Comment by rossp** [comment] 2015-04-09 22:47
In particular - have you got [`django.template.context_processors.static`](https://docs.djangoproject.com/en/1.8/ref/templates/api/#django.template.context_processors.static) defined?

**Comment by reduxionist** [comment] 2015-06-03 08:57
George,

Please see PR #330 as I believe it will fix this for you, as this is likely a duplicate of issue #286.

**Closed** 2015-06-09 23:34 UTC
